<?php
$qs = "Technické softwarové požadavky pro tento kurz nezahrnují:&newLine;
Oracle SQL Developer Data Modeler&newLine;
*Microsoft Access&newLine;
Oracle APEX application&newLine;
Všechno jsou to požadavky.&newLine;
§&newLine;
__________ model popisuji databázi z hlediska tabulek, sloupců a propojení mezi tabulkami.&newLine;
Síťový&newLine;
Objektově orientovaný&newLine;
Hierarchický&newLine;
*Relační&newLine;
§&newLine;
Výhody objektově orientovaného modelu jsou:&newLine;
Snížená údržba&newLine;
Modelování v reálném světě&newLine;
*Oboje A i B&newLine;
Ani A ani B&newLine;
§&newLine;
V relačním databázovém modelu musí být každý název tabulky unikátní. Názvy sloupců v tabulce musí být unikátní též. Lze mít dvě odlišné tabulky, které mají stejné názvy sloupců.&newLine;
*Pravda&newLine;
 Nepravda&newLine;
 §&newLine;
Co je prvním krokem v procesu vývoje databáze?&newLine;
Návrh&newLine;
Testování&newLine;
*Strategie a Analýza&newLine;
Vytváření&newLine;
§&newLine;
DBMS (SŘBD) znamená:&newLine;
Database Memory System&newLine;
*Database Management System&newLine;
Database Management Software&newLine;
Database Manipulation Systém&newLine;
§&newLine;
Která transformace ve výpočetní technice umožňuje ukládání a doručování dat přes internet?&newLine;
Desktop computing&newLine;
Grid computing&newLine;
*Cloud computing&newLine;
Mainframe computing&newLine;
§&newLine;
Informace je výsledkem kombinování, porovnávání a provádění výpočtů dat&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Jaký je rozdíl mezi informací a daty?&newLine;
*Data se promění v užitečné informace. Jsou uložená v databázi a jsou přístupná systémům a uživatelům&newLine;
Data jsou uchovávána a chápána pouze uživateli&newLine;
Informace jsou uchovávané a chápané pouze uživateli&newLine;
Informace a data nemají žádné rozdíly – jsou to dva názvy pro stejnou věc&newLine;
§&newLine;
Při dokončení procesu konceptuálního modelování musíme vzít v úvahu následující:&newLine;
Business pravidla&newLine;
Předpoklady&newLine;
Problémy&newLine;
*Vše výše uvedené&newLine;
§&newLine;
Business pravidla nám pomáhají pochopit standardizační postup, který organizace dodržuje při zpracování obrovských dat.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Všechna Business pravidla mohou být vymodelována.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Použití databázového řešení namísto flat file souboru eliminuje všechny následující potíže kromě:&newLine;
Redundance&newLine;
Nekonzistence&newLine;
Anomálie zadávání dat&newLine;
*Nesprávná data&newLine;
§&newLine;
Pokud budou během koncepčního modelování jasně sděleny informační požadavky, bude výsledkem:&newLine;
Konceptuální model, který plně neodráží business&newLine;
Některá business pravidla nemusí být zohledněna&newLine;
Zpoždění způsobená přepracováním modelu způsobená nesprávnými předpoklady&newLine;
*Dobře navržený konceptuální model&newLine;
§&newLine;
Všechny dnešní společnosti potřebují databázové systémy. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Databáze interaguje s daty a poskytuje následující možnosti:&newLine;
Načítání dat&newLine;
Vkládání dat&newLine;
Mazání dat&newLine;
*Vše výše uvedené&newLine;
§&newLine;
Vyberte business nebo odvětví, které by databázi nepotřebovalo:&newLine;
Bankovnictví&newLine;
Maloobchod&newLine;
Vědecký výzkum&newLine;
*Všechny tyto podniky by mohly mít prospěch z používání databáze.&newLine;
§&newLine;
Síťová databáze se skládá ze souboru záznamů propojených prostřednictvím odkazů.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
V hierarchickém modelu jsou data uložena jako záznamy, které jsou navzájem propojeny prostřednictvím:&newLine;
*Odkazů&newLine;
Databází&newLine;
Polí&newLine;
Primárních klíčů&newLine;
§&newLine;
Flat file soubor může obsahovat mnoho polí s duplicitními daty, která jsou náchylná k poškození dat.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Důvodem používání databází spíše než souborů byl… (vyberte 3)&newLine;
Používání bloků&newLine;
*Snížená redundance dat&newLine;
*Integrace dat, snadnější úpravy přístupu pro složité transakce&newLine;
*Dostupnost datové rozmanité sady uživatelů&newLine;
§&newLine;
Business pravidla jsou důležitá, protože:&newLine;
*Umožňují vývojáři porozumět pochopit relace a omezení zúčastněných entit&newLine;
Všechna je lze začlenit do struktury návrhu databáze&newLine;
Mohou rychle zastarat&newLine;
Jsou složité a těžko pochopitelné&newLine;
§&newLine;
SQL *Plus je používání v Oracle Academy kurzech ke spuštění SQL kódu. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
V _________ datovém modelu jsou data organizována do stromové struktury a pro načtení dat je třeba projít celým stromem počínaje kořenovým uzlem.&newLine;
Objektově orientovaném&newLine;
*Hierarchickém&newLine;
Sítovém&newLine;
Relačním&newLine;
§&newLine;
Strategie pro učení používané v tomto kurzu zahrnují:&newLine;
Školení vedené instruktorem&newLine;
Uznávanou certifikaci&newLine;
Osnovy řízené projektem&newLine;
*Všechno výše uvedené.&newLine;
§&newLine;
Dokumentace business požadavků pomáhá vývojářům řídit rozsah systému a brání uživatelům tvrdit, že nový systém nesplňuje jejich business požadavky. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Business _________ se používají k porozumění business procesů a povahy, role a rozsahu dat.&newLine;
Procesy&newLine;
Cíle&newLine;
Prohlášení o poslání &newLine;
*Pravidla&newLine;
§&newLine;
Jakmile jste se naučili, jak psát programy a vytvářet systémy, již nepotřebujete žádné vstupy ani zapojení uživatelů, protože jste dokonale schopni dodávat systémy, které podniky potřebují a chtějí&newLine;
Pravda. Uživatelé oddálí dodávku systému změnou názorů a přidáním nových požadavků&newLine;
*Nepravda. Business požadavky se mohou a budou měnit. Mohou například vzniknout nové právní požadavky.&newLine;
Pravda. Jediným požadavkem na vytvoření dokonalého systému je dokonalý programátor&newLine;
Pravda. Uživatelné stejně nikdy neví, co chtějí, proto je budování systémů nejlepší ponechat na profesionálech&newLine;
§&newLine;
Jaká z následujících transformací ve výpočetní technice vedla k nárůstu aplikací grafického uživatelského rozhraní (GUI)?&newLine;
Grid computing&newLine;
*Desktop computing&newLine;
Client/Server computing&newLine;
Mainframe computing&newLine;
§&newLine;
1:1 relace mají __________ jedna ku jedné v obou směrech.&newLine;
Pojmenování&newLine;
Optionality&newLine;
Cizí klíč&newLine;
*Kardinalitu&newLine;
§&newLine;
Součásti relace zahrnují všechny kromě:&newLine;
Kardinality&newLine;
Optionality&newLine;
Názvů&newLine;
*Relační integrity&newLine;
§&newLine;
Cizí klíč je sloupec nebo kombinace sloupců v jedné tabulce, která unikátně identifikuje řádek v jiné tabulce.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Fyzický model je odvozen z logického modelu. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Logický model se stane plánem pro návrh:&newLine;
Síťového modelu&newLine;
*Fyzického modelu&newLine;
Modelu integrity dat&newLine;
Modelu datového toku&newLine;
§&newLine;
Na co odkazuje single table? (vyberte 2)&newLine;
*Nerelační systémy, které obvykle ukládají každou tabulku a index do samostatných souborů a často nepodporují jazyk SQL&newLine;
Plně relační databázový systém jako je Microsoft SQL server nebo databázové systémy Oracle&newLine;
*Databáze, kde jsou všechna data uložena v jedné velké tabulce&newLine;
Typ metody ukládání dat do databáze, kde jsou všechny datové prvky uloženy na sebe&newLine;
§&newLine;
Určete všechny nesprávná tvrzení, která doplňují tuto větu: Primární klíč je… (vyberte 3)&newLine;
*Sada sloupců v jedné tabulce, která jednoznačně identifikuje každý řádek v jiné tabulce&newLine;
Jeden nebo více sloupců, který jednoznačně identifikuje každý řádek v této tabulce&newLine;
*Jeden sloupec, který jednoznačně identifikuje každý sloupec v tabulce&newLine;
*Pouze jeden sloupec, který musí mít hodnotu NULL&newLine;
§&newLine;
Při mapování relace pro ERD relaci musí být zahrnuty názvy relací.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Který z těchto následujících není cílem ER modelování:&newLine;
Zachytit všechny požadované informace&newLine;
Vyhledání informace logickým způsobem&newLine;
Zajistit, aby se informace objevovaly pouze jednou&newLine;
*Je přijatelné zahrnout informace, které lze odvodit&newLine;
§&newLine;
Při mapování relace pro ERD diagram musí být obě strany relace zmapovány.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Unikátní identifikátor má NULL hodnotu pro každou instanci entity po celý život instance. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Primární klíč jednoznačně identifikuje každý řádek v tabulce a je založen na __________ z logického návrhu&newLine;
*Primární UID&newLine;
Kandidátní UID&newLine;
Složené UID&newLine;
Sekundární UID&newLine;
§&newLine;
Při vytváření entit v logickém modelu musíme dodržovat tato pravidla: (vyberte 2)&newLine;
*Pojmenovat je v jednotném čísle&newLine;
Pojmenovat je v množeném čísle&newLine;
*Zahrnout atributy&newLine;
Vyloučit atributy&newLine;
§&newLine;
Které z následujících jsou vhodné názvy entit? (vyberte 2)&newLine;
*ZVÍŘE&newLine;
PSI&newLine;
ZVÍŘATA&newLine;
*PES&newLine;
§&newLine;
Které z následujících budou dobré jako unikátní identifikátory pro entitu? (vyberte 3)&newLine;
Datum narození pro dítě&newLine;
*Registrační číslo vozidla pro auto&newLine;
*ISBN číslo pro knihu&newLine;
*Osobní identifikační číslo pro osobu&newLine;
§&newLine;
V relačním databázovém systému, dalším krokem po vytvoření konceptuálního datového modelu je převedení ho na __________.&newLine;
Entitně relační datový model&newLine;
*Logický datový model&newLine;
Interní datový model&newLine;
Externí datový model&newLine;
§&newLine;
Které z následujících je důvodem pro vytváření konceptuálních modelů?&newLine;
Usnadnění diskuse, obrázek má hodnotu tisíce slov&newLine;
Tvoří důležitou ideální dokumentaci systému&newLine;
Zohledňuje vládní předpisy a zákony&newLine;
Tvoří solidní základ pro návrh fyzické databáze&newLine;
*Vše výše uvedené&newLine;
§&newLine;
Maticové diagramy jsou používány pro ověření, že všechny _________ byly identifikovány pro ERD.&newLine;
Entity&newLine;
Klíče&newLine;
Atributy&newLine;
*Relace&newLine;
§&newLine;
Optionality relací musí být buď _____ nebo _____. &newLine;
*Povinné nebo volitelné&newLine;
Single nebo Multiple&newLine;
One or (One or More)&newLine;
Obousměrná nebo jednosměrná&newLine;
§&newLine;
Která z následujících není výhodou relační databáze?&newLine;
Účinnost&newLine;
Integrita dat&newLine;
*Jedna tabulka se všemi údaji&newLine;
Méně redundance&newLine;
§&newLine;
Které z následujících tvrzení se nevztahuje na relační databáze?&newLine;
Tabulky jsou jednou ze základních součástí relační databáze&newLine;
Relační databáze jsou jednoduché na pochopení&newLine;
Relační databáze vzájemně propojují tabulky pomocí společných polí nazývaných klíče&newLine;
*Relační databáze mají silnou procedurální orientaci&newLine;
§&newLine;
__________ model zahrnuje entity, atributy, UID, relace i optionality a kardinalitu těchto položek.&newLine;
*Logický&newLine;
Hierarchický&newLine;
Fyzický&newLine;
Konceptuální&newLine;
§&newLine;
Datové modely jsou nakresleny, aby uživatelům zobrazily skutečná data, která bude jejich nový systém obsahovat; do databáze lze zadat pouze data uvedená na diagramu. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
__________ je informace, která nějakým způsobem popisuje entitu. Je to vlastnost entity a kvantifikuje, kvalifikuje, klasifikuje nebo specifikuje entitu.&newLine;
Proces&newLine;
ERD&newLine;
*Atribut&newLine;
Tabulka&newLine;
§&newLine;
Jakým typem tvaru jsou na ERD nakresleny boxy entit?&newLine;
Diamanty&newLine;
*Soft boxy&newLine;
Obdélníky&newLine;
Hard boxy&newLine;
§&newLine;
Kandidátní UID, který nebude zvolen jako primární UID se nazývá ________.&newLine;
*Sekundární UID&newLine;
Primární UID&newLine;
Složený UID&newLine;
Unikátní UID&newLine;
§&newLine;
Který symbol slouží k označení, že je určitý atribut volitelný?&newLine;
&&newLine;
“*”&newLine;
*o&newLine;
#&newLine;
§&newLine;
Atributy mají instance. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Která z následujících je pravda o kardinalitě? (vyberte 2)&newLine;
Kardinalita určuje početní číslo (jako 1, 2, 3 atd) v relaci&newLine;
*Kardinalita určuje singularitu a pluralitu ale neurčuje množné číslo.&newLine;
*Kardinalita nám říká „kolik“&newLine;
Kardinalita určuje zda je něco požadované nebo ne&newLine;
§&newLine;
ERDish je jazyk používaný pro vytváření databázových struktur v SQL.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Zachycení všech požadovaných dat je jediným cílem relačního modelování.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Flat file databáze zabraňuje duplikaci dat. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
________ jsou převedeny na řádky ve fyzickém návrhu.&newLine;
Entity&newLine;
*Instance&newLine;
Sloupce&newLine;
Atributy&newLine;
§&newLine;
Která z následujících možností by byla logickým omezením při modelování času pro entitu City?&newLine;
Je třeba sledovat denní vzorce provozu, aby bylo možné určit kolik policistů je zapotřebí.&newLine;
Lidé se rodí ve městě a lidé ve městě umírají.&newLine;
*Města mohou změnit své názvy a/nebo sdružení zemí, pokud se změní hranice země.&newLine;
Pokud děláte systém pro jakékoli francouzské město, potřebujete bezpečnostní prověrky&newLine;
§&newLine;
Který z následujících scénářů by měl být modelován tak, aby byla uchovávána historická data? (vyberte 2)&newLine;
UČITEL a VĚK&newLine;
*ZÁKAZNÍK a OBJEDNÁVKY&newLine;
DÍTĚ a VĚK&newLine;
*ZÁKAZNÍK a PLATBY&newLine;
§&newLine;
Ve fyzickém datovém modelu je relace reprezentována jako kombinace: (vyberte 2)&newLine;
*Primární klíč nebo Unikátní klíč&newLine;
Sloupec&newLine;
*Cizí klíč&newLine;
Check Constraint nebo Unikátní klíč&newLine;
§&newLine;
Při mapování barred relace mohou být primární klíč a cizí klíč stejné pole.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Název entity se převede na název tabulky vytvořením množného čísla.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
__________ relace je vytvořena když UID pro entitu zahrnuje relaci s jinou entitou.&newLine;
M:M&newLine;
1:1&newLine;
Rekurzivní&newLine;
*Barred&newLine;
§&newLine;
__________ na relaci říká, že je relace nepřenositelná (Non-Transferable).&newLine;
Hvězda&newLine;
*Diamant&newLine;
Trojúhelník&newLine;
Kruh&newLine;
§&newLine;
Jak nazýváme entitu vytvořenou při řešení M:M relace?&newLine;
Rekurzivní entita&newLine;
M:M entita&newLine;
Inclusion entita&newLine;
*Průniková entita (Intersection entity)&newLine;
§&newLine;
Jako návrhář databází si nemusíte dělat starosti s tím, kam v datamodelu uložíte konkrétní atribut, dokud se dostanete na ERD, vaše práce je hotová. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Normalizace je proces organizace atributů a entit relační databáze za účelem minimalizace&newLine;
Redundance&newLine;
Nekonzistence dat&newLine;
Anomálií&newLine;
*Všeho výše uvedeného&newLine;
§&newLine;
Business pravidlo „Zboží zasíláme až poté, co zákazníci zcela uhradí veškeré nevyrovnané zůstatky na jejich účtu“, nejlépe vynucuje:&newLine;
Udělání atributu platby jako null.&newLine;
*Najmutí programátora, aby vytvořil další kód, aby ověřil, že nebude odesláno žádné zboží, dokud nebude účet vyrovnán na null.&newLine;
Musíme důvěřovat našim zákazníkům a víme, že někdy zaplatí.&newLine;
Udělání atributu platby jako volitelný.&newLine;
§&newLine;
Normalizace entity na 1. NF se provádí odstraněním všech atributů, které obsahují vícenásobné hodnoty. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Pokud v entitě chybí sloupec – normalizace by měla identifikovat tento problém.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Modelování historických dat je volitelné. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Entitě bez opakujících se hodnot se říká, že je v _________.&newLine;
3. NF&newLine;
*1. NF&newLine;
4. NF&newLine;
2. NF&newLine;
§&newLine;
Tabulka je ve 2. NF když je tabulka v 1 NF a jaká další podmínka je splněna?&newLine;
*Neexistují žádné atributy, které nejsou funkčně závislé na celém primárním klíči relace.&newLine;
V primárních polích nejsou null hodnoty.&newLine;
Neexistují žádné opakující se skupiny.&newLine;
Neexistují žádné funkční závislosti.&newLine;
§&newLine;
Podle _________ musí být atribut závislý na celém unikátním identifikátoru jeho entity.&newLine;
4. NF&newLine;
3. NF&newLine;
1. NF&newLine;
*2. NF&newLine;
§&newLine;
Pravidlo 3. NF uvádí, že žádný Non-UID atribut nemůže záviset na jiném Non-UID atributu. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Relace můžete vytvářet pouze k Supertype, nikoli k Subtype. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Když vyřešíte M:M, jednoduše znovu nakreslíte relace mezi dvěma původními entitami, nejsou vytvářeny žádné nové entity. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Která z následujících možností je pravda o Subtype?&newLine;
Subtypy se nesmí vzájemně vylučovat.&newLine;
*Subtypy se musí vzájemně vylučovat.&newLine;
Subtypy by neměly být Exhaustive.&newLine;
Jedna instance supertypu může patřit ke dvěma subtypům.&newLine;
§&newLine;
Ve fyzickém datovém modelu je atribut prezentován jako:&newLine;
Instance&newLine;
Cizí klíč&newLine;
*Sloupec&newLine;
Řádek&newLine;
§&newLine;
Při převodu názvů atributů na sloupce se často používají ________.&newLine;
Čísla&newLine;
Mezery&newLine;
Speciální znaky&newLine;
*Zkratky&newLine;
§&newLine;
Názvy atributů jsou převedeny na názvy sloupců ___________&newLine;
*Nahrazením mezer podtržítky&newLine;
Nahrazením čísel písmeny&newLine;
Nahrazením podtržítek pomlčkami&newLine;
Nahrazením period čárkami&newLine;
§&newLine;
Zdroje business pravidel zahrnují všechny následující položky kromě:&newLine;
Postupů&newLine;
Provozních manuálů&newLine;
*Slova z úst&newLine;
Norem&newLine;
§&newLine;
Tabulka je ve 3. NF, pokud splňuje všechny databázové požadavky pro 1. NF i 2. NF a jsou vyloučeny všechny tranzitivní závislosti.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Které z následujících tvrzení o subtypech není pravda?&newLine;
Zdědí všechny supertype atributy&newLine;
Zdědí všechny supertype relace&newLine;
Nikdy neexistuje sám.&newLine;
*Musí mít vlastní subtypy.&newLine;
§&newLine;
Jiný název pro barred relaci je __________.&newLine;
*Identifikační relace&newLine;
Hierarchická relace&newLine;
Supertype relace&newLine;
Rekurzivní relace&newLine;
§&newLine;
Pokud relaci NELZE přesouvat mezi instancemi entit, které spojuje, říká se jí:&newLine;
Povinná&newLine;
Přenosná (Transferable)&newLine;
*Nepřenosná (Non-Transferable)&newLine;
Volitelná&newLine;
§&newLine;
Transformace z ER diagramu na fyzický návrh zahrnuje změnu terminologie. Ze sekundárních unikátních identifikátorů se stávají:&newLine;
Sloupce&newLine;
Constraints (omezení) primárního klíče&newLine;
*Unikátní Constraints (omezení)&newLine;
Tabulky&newLine;
§&newLine;
Názvy tabulek mohou obsahovat všechno uvedené kromě:&newLine;
*Mezer&newLine;
Písmen&newLine;
Nějakých speciálních znaků&newLine;
Čísel&newLine;
§&newLine;
Která z následujících možností ohledně normalizace není pravdivá?&newLine;
*Nemá to vliv na výkon databáze.&newLine;
Jedná se o proces organizace atributů a tabulek relační databáze, aby se minimalizovala redundance.&newLine;
Pomáhá při vkládání, aktualizace a mazání anomálií.&newLine;
Pomáhá s výkonem databáze.&newLine;
§&newLine;
Kdy je entita ve 2. NF?&newLine;
*Když jsou veškeré Non-UID atributy závislé na celém UID.&newLine;
Když jsou odstraněny atributy s opakujícími se nebo více hodnotami.&newLine;
Když žádné atributy nejsou vzájemně nezávislé a všechny jsou plně závislé na primárním klíči.&newLine;
Nic z výše uvedeného.&newLine;
§&newLine;
DBMS (SŘBD) se skládá z následujících prvků: (vyberte 3)&newLine;
*Správa paměti a úložiště&newLine;
*Dotazovací jazyk&newLine;
*Datový slovník&newLine;
Client&newLine;
§&newLine;
Která z následujících možností není cílem tohoto kurzu:&newLine;
Popis účelu relační databáze&newLine;
Popis klíčových business požadavků databáze&newLine;
*Ladění výkonu databáze&newLine;
Použití datového modelování k vytvoření databáze&newLine;
§&newLine;
_________ relace je relace mezi jednou a tou samou entitou.&newLine;
*Rekurzivní&newLine;
Hierarchická&newLine;
Povinná&newLine;
1:1&newLine;
§&newLine;
V ERD je optionality zobrazena pomocí_________.&newLine;
„Single toe“ nebo „crown foot“&newLine;
*Plných nebo přerušovaných čar&newLine;
Názvů relací&newLine;
Soft boxů&newLine;
§&newLine;
Jaký je účel unikátního identifikátoru?&newLine;
Vytvoření entity, která se nepodobá žádné jiné entitě.&newLine;
*Identifikovat jednu unikátní instanci entity pomocí jednoho nebo více atributů a/nebo relací.&newLine;
Identifikovat specifický řádek v tabulce, použitím jednoho nebo více sloupců a/nebo cizích klíčů.&newLine;
Jednoznačně určit tabulku a sloupce v této tabulce.&newLine;
§&newLine;
Unikátní identifikátory…&newLine;
*Rozlišují jednu instanci entity od všech ostatních instancí této entity.&newLine;
Rozlišují všechny entity v databázi.&newLine;
Nerozlišují nic.&newLine;
Rozlišují jednu entitu od druhé.&newLine;
§&newLine;
Primární klíče mohou obsahovat null hodnoty.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Unikátní identifikátor musí být složen z více než jednoho atributu. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Názvy entit jsou vždy v jednotném čísle.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Entity jsou obvykle _________.&newLine;
*Podstatná jména&newLine;
Příslovce&newLine;
Přídavná jména&newLine;
Slovesa&newLine;
§&newLine;
Který z atributů je volatilní (nestálý)?&newLine;
Rasa&newLine;
Datum narození&newLine;
*Věk&newLine;
Barva očí&newLine;
§&newLine;
Integrita dat zajišťuje _________ v informacích &newLine;
Anomálie&newLine;
Duplikaci&newLine;
Chyby&newLine;
*Žádnou duplikaci&newLine;
§&newLine;
V relačním modelu jsou data organizována v základní struktuře úložiště, která se nazývá __________.&newLine;
N-tice&newLine;
Pole&newLine;
Řádek&newLine;
*Tabulka&newLine;
§&newLine;
ERDish zahrnuje následující kromě:&newLine;
Optionality&newLine;
Názvů relací&newLine;
Kardinality&newLine;
*Datových hodnot&newLine;
§&newLine;
Jak je v ERD znázorněna volitelná relace?&newLine;
Šipkou&newLine;
„Crows foot“&newLine;
*Tečkovanou čarou&newLine;
Plnou čarou&newLine;
§&newLine;
Logický model zahrnuje:&newLine;
Pouze entity, atributy a relace&newLine;
Pouze entity a relace&newLine;
*Entity, atributy, unikátní identifikátory a relace&newLine;
Pouze entity, atributy a unikátní identifikátory&newLine;
§&newLine;
UID pro sadu hierarchických entit lze propagovat prostřednictvím více _________ relací.&newLine;
Arc&newLine;
*Barred&newLine;
1:1&newLine;
Rekurzivních &newLine;
§&newLine;
„Na zkoušky mohou dohlížet pouze učitelé“ je příkladem které z následujících možností?&newLine;
*Procedurální business pravidlo&newLine;
Strukturální business pravidlo&newLine;
Atribut, který se nedědí ze supertypu OSOBA a je unikátní pro subtype UČITEL&newLine;
Atribut, který by měl být uložen v entitě OSOBA&newLine;
§&newLine;
Proč je důležité se řídit pravidly normalizace?&newLine;
Snížení nadbytečných dat ve stávajícím návrhu.&newLine;
Zvýšení integrity dat a stability návrhu.&newLine;
Odstranit další typy nekonzistencí a anomálií dat.&newLine;
K identifikaci chybějících tabulek, sloupců a constraints (omezení)&newLine;
*Vše výše uvedené&newLine;
§&newLine;
Co nelze modelovat pomocí Oracle SQL Data Modeler?&newLine;
Entity, Atributy, UID&newLine;
Supertype a Subtype entity&newLine;
Rekurzivní relace&newLine;
Arc relace&newLine;
*Vše lze modelovat&newLine;
§&newLine;
Při vytváření modelu v Oracle SQL Data Modeler začnete na kartě ________.&newLine;
*Logické&newLine;
Relační&newLine;
Fyzické&newLine;
Konceptuální&newLine;
§&newLine;
Oracle SQL Data Modeler umožňuje provádět všechny následující činnosti kromě:&newLine;
Vytváření procesních, logických, relačních a fyzických modelů&newLine;
Ukládání metadat&newLine;
Zachycení business pravidel a informací&newLine;
*Ukládání dat aplikace&newLine;
§&newLine;
Proces převodu relačního modelu na logický model se nazývá reverzní inženýrství (reverse engineering.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Relační model je blíže implementačnímu řešení, usnadňuje diskusi a tvoří základ pro fyzický návrh databáze.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Kroky pro převod relačního modelu na logický model pomocí Oracle SQL Developer Data Modeler jsou:&newLine;
Výběr relačního modelu, přijetí výchozích hodnot, kliknutí na ikonu Engineer to Logical Model, kliknutí na Engineer&newLine;
Kliknutí na ikonu Engineer to Relational Model, vybrání logického modelu, kliknutí na Engineer, přijetí výchozích hodnot&newLine;
*Vybrání relačního modelu, kliknutí na ikonu Engineer to Logical Model, přijetí výchozích hodnot, kliknutí na Engineer&newLine;
Nic z výše uvedeného&newLine;
§&newLine;
Nejprve musíte vybrat logický model se kterým chcete pracovat, abyste jej mohli navrhnout na relační model.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Glosář (Glossary) lze použít jako standart pro pojmenování vašeho logického modelu.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Každý atribut v entitě se mapuje jako ________ v tabulce.&newLine;
Instance&newLine;
Primární klíč&newLine;
*Sloupec&newLine;
Řádek&newLine;
§&newLine;
Sloupce nebo kombinace sloupců v jedné tabulce, který odkazuje na primární klíč v té samé nebo jiné tabulce se nazývá:&newLine;
*Cizí klíč&newLine;
Primární klíč&newLine;
Kandidátní klíč&newLine;
Super klíč&newLine;
§&newLine;
__________ v Oracle SQL Developer Data Modeler je sada akceptovaných termínů, které lze použít v návrhu.&newLine;
Tabulka&newLine;
Ověřovací pravidlo&newLine;
Šablona&newLine;
*Glosář&newLine;
§&newLine;
V Oracle SQL Developer Data Modeler můžete vybrat, jak chcete mapovat své subtypy.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Můžeme použít pojmenovávací zkratky pomocí souboru .csv obsahující zkratky.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Constraints (omezení) primárního klíče by měla mít příponu PKEY.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Constraints (omezení) primárního klíče jsou pojmenována pomocí __________.&newLine;
Celého názvu tabulky&newLine;
*Zkráceného názvu tabulky&newLine;
Názvu cizího klíče&newLine;
UID přípony&newLine;
§&newLine;
Pojmenovávací standarty můžete definovat v Oracle SQL Developer Data Modeler pomocí:&newLine;
Glosáře&newLine;
Pojmenovávacích šablon&newLine;
Návrhových ověřovacích pravidel&newLine;
*Vše výše uvedené lze použít k definování pojmenovávacích standartů v Oracle SQL Data Modeler&newLine;
§&newLine;
V Oracle SQL Data Modeler je atribut, který přiřadíte jako primární UID, automaticky nastaven na povinný atribut a bude vytvořen jako primární v relačním modelu.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
__________ engineering je proces vytváření konceptuálního nebo logického modelu extrahováním informací ze stávajícího zdroje dat.&newLine;
Top-Down &newLine;
Target&newLine;
Forward&newLine;
*Reverse&newLine;
§&newLine;
Top-Down modelování (shora dolů) je postup zvolený při navrhování nové databáze.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Pro definování pojmenovávacích šablon v Oracle SQL Data Modeler:&newLine;
Klikněte pravým tlačítkem na název vzoru v prohlížeči objektů&newLine;
Vyberte vlastnosti, vyberte šablonu&newLine;
Upravte šablonu tak, aby používala zkratky&newLine;
*Proveďte všechny tyto kroky&newLine;
§&newLine;
_________ model je plánem skutečné implementace databáze a lze jej použít jako základ pro implementaci jakéhokoli typu DBMS (SŘBD)&newLine;
*Relační&newLine;
Konceptuální&newLine;
Databázový&newLine;
Logický&newLine;
§&newLine;
Entitně relační model nezvýrazňuje fyzická a databázová omezení. Je nezbytné transformovat ER model na relační model, který může sloužit jako základ pro definování fyzické implementace databáze.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Constraints (omezením) by měla být přidělena smysluplná jména, aby se na ně lépe odkazovalo.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Při mapování subtypů na tabulky můžeme _________.&newLine;
Použít jednu tabulku&newLine;
Použít více tabulek&newLine;
*Platnými možnostmi jsou jedna i více tabulek.&newLine;
Platná volba není ani jedna, ani více tabulek.&newLine;
§&newLine;
_________ se používá k přidávání, úpravám a mazání dat.&newLine;
Data Control Language (DCL)&newLine;
Data Definition Language (DDL)&newLine;
*Data Manipulation Language (DML)&newLine;
Data Management Language&newLine;
§&newLine;
Příkaz, který vždy odstraní všechny řádky z tabulky a ponechá tabulku prázdnou je:&newLine;
*TRUNCATE&newLine;
DELETE&newLine;
Obojí&newLine;
Ani jeden&newLine;
§&newLine;
Pokud máte ve sloupcích zavedená constraints (omezení), dojde k chybě, pokud se pokusíte porušit pravidlo omezení.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Názvy tabulek a názvy sloupců musí začínat číslem a měly by mít délku 1-30 znaků.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Při změně tabulky můžete zmenšit šířku sloupců, pokud … (vyberte 3)&newLine;
*Zmenšení šířky sloupce není menší než stávající hodnoty v daném sloupci&newLine;
Sloupec osahuje číselné hodnoty&newLine;
*Tabulky nemá žádné řádky&newLine;
*Sloupec obsahuje pouze null hodnoty&newLine;
§&newLine;
Pokud tabulky již obsahuje řádky když je přidán sloupec, nový sloupec je zpočátku null nebo má výchozí hodnotu pro všechny řádky. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Při použití _______ na tabulku, databáze ztratí všechna data v tabulce.&newLine;
ALTER&newLine;
ERASE&newLine;
*DROP&newLine;
SELECT&newLine;
§&newLine;
Který software se používá ke správě čtení a manipulaci s relační databází?&newLine;
ERD software&newLine;
Spreadsheet software (tabulkový procesor)&newLine;
Flat file software&newLine;
*DBMS (SŘBD) software&newLine;
§&newLine;
Funkce SQL jsou:&newLine;
Vkládání, aktualizace a mazání řádků v tabulce&newLine;
Dotazování na data uložená v databázi&newLine;
*Obě výše uvedené možnosti jsou funkcemi SQL&newLine;
Ani jedna z výše uvedených možností není funkcí SQL&newLine;
§&newLine;
Primární klíč musí obsahovat hodnotu, která musí být ________.&newLine;
*Unikátní&newLine;
Null&newLine;
Větší než nula&newLine;
Prázdná &newLine;
§&newLine;
Hodnota cizího klíče se musí shodovat s existující hodnotou primárního klíče, jinak musí mít hodnotu null.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Chcete-li zobrazit všechna pole a záznamy v tabulce employees, můžete spustit následující dotaz:&newLine;
SELECT all FROM employees;&newLine;
SELECT columns FROM employees;&newLine;
*SELECT * FROM employees;&newLine;
SELECT # FROM employees;&newLine;
Žádný z výše uvedených&newLine;
§&newLine;
Z možnosti ________ můžete nahrát a uložit SQL skript.&newLine;
Utilities &newLine;
Object browser&newLine;
*SQL Scripts&newLine;
RESTful Services&newLine;
SQL commands&newLine;
§&newLine;
_________ v dotazu přichází bezprostředně za SELECT a FROM.&newLine;
*WHERE&newLine;
ORDER BY&newLine;
IF&newLine;
GROUP BY&newLine;
§&newLine;
Aplikační programy nám umožňují ________.&newLine;
Zkontrolovat email&newLine;
Vytvářet dokumenty&newLine;
Upravit fotogramy&newLine;
*Vše výše uvedené&newLine;
§&newLine;
V základním dotazu následují za slovem FROM pole, která se mají zobrazit.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Constraints (omezení) zajišťují konzistenci a integritu databáze.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Data Definition Language (DDL) provádí všechny následující činnosti kromě:&newLine;
Vytváření tabulek&newLine;
Změnění tabulek&newLine;
*Vkládání dat do tabulek&newLine;
Přidávání constraints (omezení) do tabulek&newLine;
§&newLine;
Fáze SQL processingu jsou Parsing, Optimalizace, Generování řádkových zdrojů a _______.&newLine;
Analýza&newLine;
*Provedení&newLine;
Zobrazení&newLine;
Nic z výše uvedeného&newLine;
§&newLine;
Typ SQL příkazu, který se používá k úpravě dat, je:&newLine;
DDL&newLine;
DCL&newLine;
TCL&newLine;
*DML&newLine;
§&newLine;
Tabulka je základní strukturou úložiště RDBMD (relační databáze).&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Kolekce příkazů SML, které tvoří logickou jednotku práce se nazývá _________.&newLine;
*Transakce&newLine;
Block&newLine;
Příkaz&newLine;
Výpis&newLine;
§&newLine;
Lze odstranit řádek, který obsahuje primární klíč, který se používá jako cizí klíč v jiné tabulce.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Abyste mohli používat počítačovou aplikaci, musíte pochopit, jak je postavena a jak funguje uvnitř.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Pomocí ________ můžete logicky spojit data z více tabulek.&newLine;
Datových hodnot&newLine;
*Cizích klíčů&newLine;
Check constraints&newLine;
Unikátních klíčů&newLine;
§&newLine;
Typ SQL příkazů, který se používá k definování databázových struktur je:&newLine;
*DDL&newLine;
TCL&newLine;
DCL&newLine;
DML&newLine;
§&newLine;
Když definujete tabulku, můžete určit, že sloupci by měla být dána výchozí hodnota pomocí LITERAL možnosti.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Které SQL klíčové slovo se používá k hodnocení v top-n-analýze?&newLine;
*ROWNUM&newLine;
GROUP BY&newLine;
WHERE&newLine;
ORDER BY&newLine;
§&newLine;
Top-n-analýza se používá, když chcete načíst pouze nejvyšší počet záznamů ze sady výsledků.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Jaký typ spojení je následující příkaz? SELECT e.EMPLOYEE_ID, e.last_NAME, d.DEPARTMENT_ID, d.DEPARTMENT_NAME, d.LOCATION_ID&newLine;
OUTER JOIN (vnější)&newLine;
INNER JOIN (vnitřní)&newLine;
*CROSS JOIN (křížové)&newLine;
NATURAL JOIN (přirozené)&newLine;
§&newLine;
Self-join lze použít, když jsou v tabulce dvě pole se stejnými daty, která mají různé významy.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Spojení mezi dvěma tabulkami, které vrací výsledky INNER join (vnitřní), stejně jako nesrovnatelné řádky z levé (nebo pravé) tabulky, se nazývá levé (nebo pravé) OUTER join (vnější).&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Logická podmínka kombinuje výsledek dvou složkových podmínek k vytvoření jediného výsledku na základě těchto podmínek nebo invertuje výsledek jedné podmínky.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Co z následujících se používá pro libovolný počet znaků v SQL?&newLine;
*%&newLine;
&&newLine;
#&newLine;
||&newLine;
§&newLine;
Uživatelé si mohou prohlížet data, která právě mění jiný uživatel.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Značku v aktuální transakci můžete vytvořit pomocí příkazu SAVEPOINT.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Spojení tabulek s klauzulemi NATURAL JOIN, USING nebo ON má za následek ________join (spojení). (vyberte 2)&newLine;
CROSS&newLine;
OUTER&newLine;
*INNER&newLine;
*Equi-join&newLine;
§&newLine;
___________ je podmínka spojení obsahující něco jiného než operátor rovnosti (equality operator).&newLine;
OUTER JOIN&newLine;
*NONEQUIJOIN&newLine;
CROSS JOIN&newLine;
INNER JOIN&newLine;
§&newLine;
Lze použít ________ k dočasnému uložení hodnot při provádění dotazu.&newLine;
*Substituční proměnné&newLine;
Databázové tabulky&newLine;
Databázové pole&newLine;
Doslovné hodnoty (literál)&newLine;
§&newLine;
Literály lze použít v rámci příkazu SELECT.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Příkaz DESCRIBE zobrazuje o tabulce následující kromě:&newLine;
Datových typů&newLine;
Primárních klíčů&newLine;
Názvů polí&newLine;
*Datových hodnot&newLine;
§&newLine;
Pokud aritmetický výraz obsahuje více než jeden operátor, vyhodnotí se nejprve _______.&newLine;
Násobení a dělení&newLine;
Sčítání a odčítání&newLine;
Umocňování&newLine;
*Cokoli v závorkách&newLine;
§&newLine;
Který operátor se používá k zobrazení řádků na základě seřazeného rozsahu hodnot?&newLine;
*BETWEEN&newLine;
IN&newLine;
NOT NULL&newLine;
LIKE&newLine;
§&newLine;
Jaký je výsledek provedení následujícího příkazu SELECT EMPLOYEE_ID, LAST NAME, JOB_ID, DEPARTMENT_ID AS 'DEPTID' FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;&newLine;
Vyzve uživatele k získání dalších informací.&newLine;
*Zobrazí EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID z tabulky EMPLOYEES kde je department id 90.&newLine;
Zobrazí EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, DEPTID z tabulky EMPLOYEES kde je department id 90.&newLine;
Zobrazí chybu.&newLine;
§&newLine;
_________ vám dávají větší flexibilitu a kontrolu při změně dat a zajišťují konzistenci dat v případě selhání procesu uživatele nebo selhání systému.&newLine;
Procedury&newLine;
Funkce&newLine;
*Transakce&newLine;
Bloky kódu (code blocks)&newLine;
§&newLine;
Null je totéž jako nula nebo prázdné místo. Pravda nebo ne?&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Chcete-li ve výsledku vyloučit duplicitní řádky, zahrňte do klauzule SELECT klíčové slovo ________.&newLine;
IF&newLine;
WHERE&newLine;
*DISTINCT&newLine;
DESCRIBE&newLine;
§&newLine;
Vybrané sloupce tabulky můžete zobrazit jejich uvedením v klauzuli ________.&newLine;
WHERE&newLine;
IF&newLine;
*SELECT&newLine;
FROM&newLine;
§&newLine;
Za kvalifikátorem DISTINCT můžete zadat více sloupců.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Klauzule _______ vytváří Equi-join mezi dvěma tabulkami pomocí jednoho sloupce se stejným názvem bez ohledu na datový typ.&newLine;
NATURAL JOIN&newLine;
EQUI-JOIN&newLine;
ON&newLine;
*USING&newLine;
§&newLine;
Spojení mezi dvěma tabulkami, které vrací výsledky INNER (vnitřní) join a také výsledky levého a pravého spojení je ________.&newLine;
CROSS JOIN&newLine;
*FULL OUTER&newLine;
TOTAL OUTER&newLine;
INNER OUTER&newLine;
§&newLine;
Kroky k vytvoření Glossary (glosáře) ze stávajícího logického modelu jsou:&newLine;
*Kliknout pravým na logický model, vybrat Create Glossary from Logical Model&newLine;
Dvakrát kliknou na logický model&newLine;
Kliknout pravým na relační model, vybrat Create Glossary from Relational Model&newLine;
Nic z výše uvedeného&newLine;
§&newLine;
DDL znamená:&newLine;
Data Distribution Language&newLine;
Data Definers Language&newLine;
*Data Definition Language&newLine;
Nic z výše uvedeného&newLine;
§&newLine;
Pomocí možnosti _________ lze označit jeden nebo více sloupců jako nepoužívané.&newLine;
*SET UNUSED&newLine;
MARK UNUSED&newLine;
TRUNCATE&newLine;
DELETE&newLine;
§&newLine;
Constraint (omezení) můžete pojmenovat nebo Oracle server vygeneruje název pomocí formátu SYS_Cn.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Relační databáze ukládají data do dvourozměrné matice známé jako ________.&newLine;
Flat file&newLine;
Entita&newLine;
*Tabulka&newLine;
Databáze&newLine;
§&newLine;
Výběr konkrétních sloupců z tabulky, které se mají zobrazit v dotazu, se nazývá ________.&newLine;
Třídění&newLine;
Vylučování&newLine;
Výběr&newLine;
*Projekce&newLine;
§&newLine;
Literál může být všechno následující, kromě:&newLine;
Datumu&newLine;
*Výpočtu&newLine;
Charakteru&newLine;
Čísla&newLine;
§&newLine;
V příkazu SELECT lze použít klauzuli _______ k řazení řádků.&newLine;
WHERE&newLine;
*ORDER BY&newLine;
SORT&newLine;
ORDER&newLine;
§&newLine;
Substituční proměnné se používají, když chcete za podmínek požadovat různá kritéria.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Která tvrzení nejsou pravdivá? (vyberte 2)&newLine;
Můžete seřadit podle sloupce, který není v SELECT listu.&newLine;
Výsledky dotazu můžete seřadit zadáním číselné pozice sloupce v klauzuli SELECT.&newLine;
*Výsledky dotazu nemůžete seřadit podle více než jednoho sloupce.&newLine;
*V klauzuli ORDER BY nemůžete použít alias sloupce.&newLine;
§&newLine;
Příkaz UPDATE upravuje hodnoty konkrétního řádku nebo řádků, pokud je zadána klauzule _______.&newLine;
*SET&newLine;
WHERE&newLine;
MODIFY&newLine;
VALUE&newLine;
§&newLine;
Příkaz TRUNCATE je příkazem Data Definition Language (DDL) a nevytváří žádné informace o vrácení zpět (rollback).&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Data Manipulation Language (DML) zahrnuje všechny následující položky kromě:&newLine;
*COMMIT&newLine;
INSERT&newLine;
DELETE&newLine;
UPDATE&newLine;
§&newLine;
Není povinné specifikovat seznam sloupců v INSERT. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
CARTESIAN nebo CROSS join se vytvoří, když je podmínka spojení vynechána.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
_________JOIN klauzule vytváří křížový produkt dvou tabulek.&newLine;
*CROSS&newLine;
OUTER&newLine;
CARTESIAN&newLine;
INNER&newLine;
§&newLine;
V možnostech APEX SQL Workshop a Object Browser můžete zobrazit rozložení tabulek.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Který operátor se používá k zobrazení řádků na základě seřazeného rozsahu hodnot?&newLine;
IN&newLine;
NOT NULL&newLine;
LIKE&newLine;
*BETWEEN&newLine;
§&newLine;
Řetězce znaků a data v klauzuli WHERE musí být uzavřeny jednoduchými uvozovkami (' ').&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Podle pravidel priority, který operátor bude vyhodnocen jako první?&newLine;
*AND&newLine;
OR&newLine;
Oba jsou na stejné prioritní úrovni.&newLine;
§&newLine;
Transakce začíná, když dojde k prvnímu příkazu DML, a končí, když dojde k jednomu z následujících …&newLine;
Je vydán příkaz COMMIT nebo ROLLACK.&newLine;
Je vydán příkaz DDL, například CREATE.&newLine;
*Jedno z výše uvedených tvrzení.&newLine;
Nic z výše uvedeného.&newLine;
§&newLine;
_________ lze nalézt na průsečíku řádku a sloupce a obsahuje jednu hodnotu.&newLine;
*Pole&newLine;
Tabulku&newLine;
Instanci&newLine;
Entitu&newLine;
§&newLine;
Pro připojení k databázi Oracle musíte použít client program. Pravda nebo ne?&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Výchozí pořadí můžete přepsat pomocí závorek kolem výrazů, které chcete vypočítat jako první.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Můžete použít Application Express (APEX) pro …&newLine;
Rozvíjení a rozšiřování vašich dovedností s databází Oracle, SQL a PL/SQL.&newLine;
Získání přístupu k příkladům SQL a PL/SQL sdílené komunitou vývojářů Oracle.&newLine;
*APEX lze použít pro obě výše uvedené funkce.&newLine;
APEX nelze použít pro žádnou z výše uvedených funkcí.&newLine;
§&newLine;
Jakmile vytvoříte tabulku, můžete pomocí příkazu ________ potvrdit, že byla vytvořena. (vyberte 2)&newLine;
LIST &newLine;
*SELECT&newLine;
*DESCRIBE&newLine;
ORDER BY&newLine;
§&newLine;
Constraints (omezení) nelze přidat do tabulky po jejím vytvoření.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Když definujete tabulku, můžete určit, že sloupce by měla být dána výchozí hodnota pomocí možnosti LITERAL.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Který sloupec alias je neplatný?&newLine;
“FIRST NAME“&newLine;
First_Name&newLine;
“First Name“&newLine;
*First Name&newLine;
§&newLine;
Který dvě tvrzení jsou správná?&newLine;
*Klíčová slova nelze zkrátit ani rozdělit mezi řádky.&newLine;
*SQL příkazy nerozlišují velká a malá písmena.&newLine;
SQL příkazy rozlišují velká a malá písmena.&newLine;
Klíčová slova mohou být zkrácena nebo rozdělena mezi řádky.&newLine;
§&newLine;
Příkaz DESCRIBE popisuje výsledky dotazu.&newLine;
Pravda&newLine;
*Nepravda&newLine;
§&newLine;
Klauzule _______ vytvoří Equi-join mezi dvěma tabulkami pomocí jednoho sloupce z každé tabulky bez ohledu na název nebo datový typ.&newLine;
CROSS JOIN&newLine;
*ON&newLine;
USING&newLine;
NATURAL JOIN&newLine;
§&newLine;
Klauzule ______ join je založena na všech sloupcích ve dvou tabulkách, které mají stejný název a stejný datový typ.&newLine;
USING&newLine;
OUTER JOIN&newLine;
*NATURAL JOIN&newLine;
CROSS JOIN&newLine;
§&newLine;
K automatickému potvrzení dojde, když _______. (vyberte 2)&newLine;
*Je proveden TCL příkaz.&newLine;
Je proveden DML příkaz.&newLine;
Je proveden příkaz SELECT.&newLine;
*Je proveden DDL příkaz.&newLine;
§&newLine;
Strukturovaný dotazovací jazyk (SQL) je deklarativní jazyk založený na množinách používaný pro přístup k datům v databázi Oracle.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Sloupce bez NOT NULL constraint (omezení) mohou standartně obsahovat nulové hodnoty.&newLine;
*Pravda&newLine;
Nepravda&newLine;
§&newLine;
Operátor _______ vyžaduje, aby byla splněna některá z podmínek komponent.&newLine;
BETWEEN&newLine;
AND&newLine;
*OR&newLine;
EITHER&newLine;
§&newLine;
Podmínka _______ testuje null hodnoty.&newLine;
ISN’T NULL&newLine;
NULL&newLine;
*IS NULL&newLine;
NULLABLE";
?>